export const getCropsData = (isArabic) => ({
  Cotton: {
    icon: "☁️",
    min: 50,
    max: 70,
    duration: "180 days",
    nutrients: "Ammonium Nitrate",
    irrigation: "Every 10-15 days",
    season: "Summer",
    yieldTons: 1.5,
    pricePerTon: 45000,
    soilPh: "6.0 - 7.5",
    sunlight: "Full Sun",
    diseases: "Boll Rot",
    info: "Requires deep soil preparation.",
    plantingDates: "March - May",
    whyPlanted: "Major cash crop in Egypt, known globally for its high-quality long-staple fibers.",
    difficulty: "Hard",
    funFact: "Egyptian cotton is considered the finest in the world due to its extra-long staples!",
    tools: ["Hand trowel", "Pruning shears", "Drip irrigation kit"],
  },
  Wheat: {
    icon: "🌾",
    min: 40,
    max: 60,
    duration: isArabic ? "١٥٠ يوم" : "150 days",
    nutrients: isArabic ? "يوريا" : "Urea",
    irrigation: isArabic ? "٤-٥ مرات/موسم" : "4-5 times/season",
    season: isArabic ? "الشتاء" : "Winter",
    yieldTons: 3,
    pricePerTon: 13000,
    soilPh: "6.0 - 7.0",
    sunlight: isArabic ? "شمس كاملة" : "Full Sun",
    diseases: isArabic ? "الصدأ" : "Rust",
    info: isArabic ? "رطوبة حيوية أثناء الإزهار." : "Critical moisture needed during flowering.",
    plantingDates: isArabic ? "نوفمبر - ديسمبر" : "November - December",
    whyPlanted: isArabic ? "محصول أساسي للأمن الغذائي؛ أهم محصول استراتيجي للخبز في مصر." : "Essential food security crop; Egypt's most critical strategic staple for bread.",
    difficulty: isArabic ? "متوسط" : "Medium",
    funFact: isArabic ? "القمح كان من أوائل المحاصيل التي زرعها الإنسان قبل أكثر من ١٠٠٠٠ عام!" : "Wheat was one of the first crops ever cultivated by humans, dating back over 10,000 years!",
    tools: isArabic ? ["آلة بذر", "منجل", "حصادة"] : ["Seed drill", "Sickle", "Harvester"],
  },
  "Sugar Cane": {
    icon: "🎋",
    min: 70,
    max: 90,
    duration: "360 days",
    nutrients: "Potassium Sulfate",
    irrigation: "High frequency",
    season: "Year-round",
    yieldTons: 40,
    pricePerTon: 1500,
    soilPh: "6.0 - 8.5",
    sunlight: "Full Sun",
    diseases: "Smut",
    info: "Requires excellent drainage.",
    plantingDates: "February - March",
    whyPlanted: "Primary source of sugar production in Upper Egypt, highly profitable for local farmers.",
    difficulty: "Medium",
    funFact: "Sugar cane is a giant grass that can grow up to 20 feet tall!",
    tools: ["Machete", "Tractor", "Drip irrigation line"],
  },
  Tomato: {
    icon: "🍅",
    min: 60,
    max: 80,
    duration: isArabic ? "٩٠ يوم" : "90 days",
    nutrients: "NPK 15-15-15",
    irrigation: isArabic ? "يومياً في الصباح الباكر" : "Daily early morning",
    season: isArabic ? "كل الفصول" : "All seasons",
    yieldTons: 20,
    pricePerTon: 6000,
    soilPh: "6.0 - 6.8",
    sunlight: isArabic ? "شمس كاملة" : "Full Sun",
    diseases: isArabic ? "اللفحة" : "Blight",
    info: isArabic ? "الرطوبة المستمرة تمنع تشقق الثمار." : "Consistent moisture prevents fruit cracking.",
    plantingDates: isArabic ? "متعدد (فبراير-مارس، سبتمبر-أكتوبر)" : "Multiple (Feb-Mar, Sep-Oct)",
    whyPlanted: isArabic ? "طلب محلي مرتفع جداً طوال العام؛ محصول متعدد الاستخدامات للسوق الطازجة والتصنيع." : "Extremely high local demand year-round; versatile crop for fresh market and processing.",
    difficulty: isArabic ? "معتدل" : "Moderate",
    funFact: isArabic ? "هل تعلم أن الطماطم من الناحية النباتية تعتبر من التوتيات؟" : "Did you know tomatoes are technically berries?",
    tools: isArabic ? ["مجرفة يدوية", "مقصات تقليم", "أقفاص طماطم"] : ["Hand trowel", "Pruning shears", "Tomato cages"],
  },
  Cucumber: {
    icon: "🥒",
    min: 60,
    max: 85,
    duration: isArabic ? "٥٠-٧٠ يوم" : "50-70 days",
    nutrients: isArabic ? "نترات البوتاسيوم" : "Potassium Nitrate",
    irrigation: isArabic ? "يومياً في الصباح الباكر" : "Daily early morning",
    season: isArabic ? "متعدد (الربيع، الصيف)" : "Multiple (Spring, Summer)",
    yieldTons: 8,
    pricePerTon: 5000,
    soilPh: "6.0 - 6.8",
    sunlight: isArabic ? "شمس كاملة" : "Full Sun",
    diseases: isArabic ? "البياض الدقيقي" : "Powdery Mildew",
    info: isArabic ? "يتطلب تعريشة لتوفير المساحة" : "Requires trellising to save space.",
    plantingDates: isArabic ? "فبراير - أبريل" : "February - April",
    whyPlanted: isArabic ? "محصول سريع النمو ومطلوب بقوة في الأسواق المحلية والمطاعم." : "Fast-growing crop with strong demand in local markets and restaurants.",
    difficulty: isArabic ? "سهل" : "Easy",
    funFact: isArabic ? "الخيار يتكون من ٩٥٪ ماء!" : "Cucumbers are 95% water!",
    tools: isArabic ? ["مقص تقليم", "تعريشة", "قفازات"] : ["Pruning shears", "Trellis", "Gloves"],
  },
  Citrus: {
    icon: "🍊",
    min: 60,
    max: 75,
    duration: "Perennial",
    nutrients: "Zinc, Iron",
    irrigation: "Regular cycles",
    season: "Winter",
    yieldTons: 15,
    pricePerTon: 8000,
    soilPh: "5.5 - 6.5",
    sunlight: "Full/Partial Sun",
    diseases: "Citrus Canker",
    info: "Prefers sandy-loamy Delta soils.",
    plantingDates: "February - April (Saplings)",
    whyPlanted: "Major export crop; Egypt is one of the world's leading exporters of oranges.",
    difficulty: "Hard",
    funFact: "Citrus trees can live and produce fruit for over 50 years!",
    tools: ["Pruning saws", "Harvesting bags", "Sprayers"],
  },
  Rice: {
    icon: "🍚",
    min: 70,
    max: 90,
    duration: "120 days",
    nutrients: "Ammonium Sulfate",
    irrigation: "Continuous flooding",
    season: "Summer",
    yieldTons: 4.2,
    pricePerTon: 16000,
    soilPh: "5.5 - 6.5",
    sunlight: "Full Sun",
    diseases: "Blast",
    info: "Requires clayey soils retaining water.",
    plantingDates: "April - May",
    whyPlanted: "Crucial summer staple crop that helps reclaim saline soils in the Northern Delta.",
    difficulty: "Hard",
    funFact: "Rice provides more than one-fifth of the calories consumed worldwide by humans!",
    tools: ["Transplanter", "Water pump", "Sickle"],
  },
  Maize: {
    icon: "🌽",
    min: 55,
    max: 75,
    duration: "110 days",
    nutrients: "Urea & Superphosphate",
    irrigation: "Every 7-10 days",
    season: "Summer",
    yieldTons: 3.5,
    pricePerTon: 12500,
    soilPh: "5.8 - 7.0",
    sunlight: "Full Sun",
    diseases: "Late Wilt",
    info: "Highly sensitive to drought during pollination.",
    plantingDates: "May - June",
    whyPlanted: "Dual-purpose crop used for human consumption and vital livestock feed.",
    difficulty: "Easy",
    funFact: "An average ear of maize has 800 kernels arranged in 16 rows!",
    tools: ["Planter", "Hoe", "Sprinkler"],
  },
  Potato: {
    icon: "🥔",
    min: 60,
    max: 80,
    duration: "105 days",
    nutrients: "Potassium Chloride",
    irrigation: "Every 5-7 days",
    season: "Winter",
    yieldTons: 12,
    pricePerTon: 8000,
    soilPh: "5.2 - 6.5",
    sunlight: "Full Sun",
    diseases: "Late Blight",
    info: "Prefers well-drained sandy-loam soils.",
    plantingDates: "Jan-Feb (Summer), Sep-Oct (Winter)",
    whyPlanted: "High-value export commodity and fundamental local vegetable.",
    difficulty: "Moderate",
    funFact: "Potatoes were the first vegetable to be grown in space!",
    tools: ["Spade", "Hoe", "Potato fork"],
  },
  Clover: {
    icon: "☘️",
    min: 50,
    max: 70,
    duration: "180 days (multi-cut)",
    nutrients: "Phosphorus",
    irrigation: "Every 12-15 days",
    season: "Winter",
    yieldTons: 35,
    pricePerTon: 2200,
    soilPh: "6.0 - 7.5",
    sunlight: "Full/Partial Sun",
    diseases: "Root Rot",
    info: "Primary animal feed crop in Egypt (Berseem).",
    plantingDates: "September - November",
    whyPlanted: "The most important forage crop for livestock; excellent for nitrogen fixation in soil.",
    difficulty: "Easy",
    funFact: "Don't mistake clover for just livestock feed; its blossoms are the secret behind exceptional honey.",
    tools: ["Seed spreader", "Scythe", "Rake"],
  },
  Onion: {
    icon: "🧅",
    min: 45,
    max: 65,
    duration: "140 days",
    nutrients: "NPK 10-10-20",
    irrigation: "Every 10 days",
    season: "Winter",
    yieldTons: 15,
    pricePerTon: 7500,
    soilPh: "6.0 - 7.0",
    sunlight: "Full Sun",
    diseases: "Downy Mildew",
    info: "Dry harvest period is crucial for storage.",
    plantingDates: "August - October",
    whyPlanted: "Key ingredient in local cuisine and a highly demanded export crop to Europe and Arab nations.",
    difficulty: "Moderate",
    funFact: "Onions make you cry because they release a sulfur gas when cut!",
    tools: ["Hand trowel", "Dibber", "Hoe"],
  },
});
