import fs from 'fs';
import sequelize from './config/database.js';

async function generateInserts() {
  try {
    await sequelize.authenticate();
    const tables = await sequelize.query("SHOW TABLES", { type: sequelize.QueryTypes.SHOWTABLES });
    
    let sql = `-- Database Dump\n-- Generated by Script\n\n`;
    
    for (const table of tables) {
      if (table === 'SequelizeMeta') continue;
      
      const rows = await sequelize.query(`SELECT * FROM \`${table}\``, { type: sequelize.QueryTypes.SELECT });
      if (rows.length === 0) continue;
      
      sql += `-- Table: ${table}\n`;
      for (const row of rows) {
        const columns = Object.keys(row).map(c => `\`${c}\``).join(', ');
        const values = Object.values(row).map(v => {
          if (v === null) return 'NULL';
          if (typeof v === 'string') return `'${v.replace(/'/g, "''").replace(/\\/g, "\\\\")}'`;
          if (typeof v === 'object' && v instanceof Date) return `'${v.toISOString().slice(0, 19).replace('T', ' ')}'`;
          return v;
        }).join(', ');
        
        sql += `INSERT INTO \`${table}\` (${columns}) VALUES (${values});\n`;
      }
      sql += '\n';
    }
    
    fs.writeFileSync('database_insert_queries.sql', sql);
    console.log('Successfully generated database_insert_queries.sql');
    process.exit(0);
  } catch (err) {
    console.error('Error:', err);
    process.exit(1);
  }
}

generateInserts();
